# Generated by Django 4.2.3 on 2024-03-10 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название категории",
                        max_length=10,
                        verbose_name="Название категории",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание категории",
                        max_length=100,
                        verbose_name="Описание категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="CategoryNomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Номинации категорий",
                "verbose_name_plural": "Номинации категорий",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название мероприятия",
                        max_length=50,
                        verbose_name="Название мероприятия",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                (
                    "owners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="owner_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник",
                "verbose_name_plural": "Участники",
            },
        ),
        migrations.CreateModel(
            name="MemberNomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url_video", models.TextField(blank=True, default="")),
                ("url_message_video", models.TextField(blank=True, default="")),
                (
                    "category_nomination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categ",
                        to="events.categorynomination",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membernom",
                        to="events.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Номинация участника",
                "verbose_name_plural": "Номинации участника",
            },
        ),
        migrations.CreateModel(
            name="Nomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название номинации",
                        max_length=50,
                        verbose_name="Название номинации",
                    ),
                ),
                ("photos_conf", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Номинация",
                "verbose_name_plural": "Номинации",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("score_retail", models.JSONField(default=None, null=True)),
                (
                    "event_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member_nomination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="events.membernomination",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка",
                "verbose_name_plural": "Оценки",
            },
        ),
        migrations.CreateModel(
            name="NominationAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("max_score", models.IntegerField(default=5)),
                (
                    "nomination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute",
                        to="events.nomination",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberNominationPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название фотографии",
                        max_length=50,
                        verbose_name="Название фотографии",
                    ),
                ),
                (
                    "before_after",
                    models.CharField(
                        choices=[("BE", "До"), ("AF", "После")], max_length=2
                    ),
                ),
                (
                    "member_nomination",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photos",
                        to="events.membernomination",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categories_in_EventCategoryModel",
                        to="events.category",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="events.event"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категории мероприятия",
                "verbose_name_plural": "Категории мероприятий",
            },
        ),
        migrations.AddField(
            model_name="categorynomination",
            name="event_category",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="events.eventcategory",
            ),
        ),
        migrations.AddField(
            model_name="categorynomination",
            name="event_staff",
            field=models.ManyToManyField(
                blank=True, related_name="staffs", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="categorynomination",
            name="nomination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nom",
                to="events.nomination",
            ),
        ),
        migrations.AddConstraint(
            model_name="result",
            constraint=models.UniqueConstraint(
                models.F("member_nomination"),
                models.F("event_staff"),
                name="unique_lower_name_category",
            ),
        ),
    ]
