# Generated by Django 4.2.3 on 2024-03-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="membernomination",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
