# Generated by Django 4.2.3 on 2024-04-28 17:34

from django.db import migrations, models

import RateOnline.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_membernomination_is_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="membernominationphoto",
            name="optimized_photo",
            field=models.ImageField(
                default=None,
                null=True,
                storage=RateOnline.storage_backends.PrivateMediaStorage,
                upload_to="optimized_photos/",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                storage=RateOnline.storage_backends.PrivateMediaStorage, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="membernominationphoto",
            name="photo",
            field=models.ImageField(
                storage=RateOnline.storage_backends.PrivateMediaStorage, upload_to=""
            ),
        ),
    ]
